#! /bin/sh -e

case "$1" in
    configure)
    if [ "`dpkg-divert --list|grep kdesudo$`" != "" ]; then
        dpkg-divert --package kdesudo --rename --remove \
            /usr/lib/kde4/libexec/kdesu
    fi
    update-alternatives --install /usr/lib/kde4/libexec/kdesu kdesu /usr/lib/kde4/libexec/kdesu-distrib/kdesu 50
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
