#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/lyx 2.0.2-1 -- "$@"
# End automatically added section

# Automatically added by dhpython:
if which pyclean >/dev/null 2>&1; then
	pyclean -p lyx-common 
else
	dpkg -L lyx-common | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
