#! /bin/sh

set -e

case "$1" in
       purge)

		rm -f \
			/etc/nullmailer/defaultdomain \
			/etc/nullmailer/defaultdomain.dpkg-* \
			/etc/nullmailer/remotes \
			/etc/nullmailer/remotes.dpkg-* \
			/etc/nullmailer/adminaddr \
			/etc/nullmailer/adminaddr.dpkg-* \
			/etc/nullmailer/defaulthost \
			/etc/nullmailer/defaulthost.dpkg-*

        ;;

esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d nullmailer remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
