#! /bin/sh

set -e

case "$1" in
    remove|upgrade|deconfigure)
		rm -f /var/spool/nullmailer/trigger
        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installinit
if [ -x "/etc/init.d/nullmailer" ] || [ -e "/etc/init/nullmailer.conf" ]; then
	invoke-rc.d nullmailer stop || exit $?
fi
# End automatically added section


exit 0
