#! /bin/sh

set -e

if [ "$1" = configure ]; then
    files=$(dpkg -L libpython2.7-dbg:amd64 | sed -n '/^\/usr\/lib\/python2.7\/.*\.py$/p')
    if [ -n "$files" ]; then
	/usr/bin/python2.7 -E -S /usr/lib/python2.7/py_compile.py $files
	if grep -sq '^byte-compile[^#]*optimize' /etc/python/debian_config; then
	    /usr/bin/python2.7 -E -S -O /usr/lib/python2.7/py_compile.py $files
	fi
    else
	echo >&2 "python2.7-dbg: can't get files for byte-compilation"
    fi
fi



exit 0
