#!/bin/bash

set -e

case "$1" in
	remove|abort-install)
		rm -Rf "/opt/sublime_text" \
			"/usr/share/icons/hicolor/16x16/apps/sublime-text.png" \
			"/usr/share/icons/hicolor/32x32/apps/sublime-text.png" \
			"/usr/share/icons/hicolor/48x48/apps/sublime-text.png" \
			"/usr/share/icons/hicolor/128x128/apps/sublime-text.png" \
			"/usr/share/icons/hicolor/256x256/apps/sublime-text.png"
		#if [ -x /usr/bin/xdg-desktop-menu ]; then
		#	xdg-desktop-menu uninstall --mode system /usr/share/applications/sublime-text.desktop
		#fi
	;;
	purge)
		rm -Rf "/var/cache/sublime-text"
	;;
esac

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
