#!/bin/sh

set -e

mkdir -m2775 -p /usr/local/share/zsh/site-functions && chown root:staff \
               /usr/local/share/zsh/site-functions || true

# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/zsh zsh-common 5.0.7-3 -- "$@"
# End automatically added section


exit 0
