#!/bin/sh

set -e

case "$1" in
    (remove|deconfigure)
        rmdir /usr/local/share/zsh/site-functions || true
        rmdir /usr/local/share/zsh || true
    ;;
    (upgrade)
    ;;

    (failed-upgrade)
    ;;

    (*)
	echo "prerm called with unknown argument \`$1'" >&2
	exit 0
    ;;
esac

# Automatically added by dh_installdeb
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/zsh zsh-common 5.0.7-3 -- "$@"
# End automatically added section


exit 0
